[general]
# import any custom files
import = ["~/.config/alacritty/themes/dracula.toml"]

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[font]
normal = { family = "LiberationMono", style = "Regular" }
bold = { family = "LiberationMono", style = "Bold" }
italic = { family = "LiberationMono", style = "Italic" }
size = 12.0

[window]
opacity = 0.75
