[general]
import = ["./themes/zenbones.toml"]

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[font]
normal = { family = "LiberationMono", style = "Regular" }
bold = { family = "LiberationMono", style = "Bold" }
italic = { family = "LiberationMono", style = "Italic" }
size = 12.0
