# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# enable vim movements
set-window-option -g mode-keys vi

# rebind r to reload source file
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# resize panes and splits
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5

# setup tpm and any plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
# set-option -g @plugin 'b0o/tmux-autoreload'

run '~/.tmux/plugins/tpm/tpm'
